# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\TuckerVana\PycharmProjects\GUI Project 2.0\PyGMI-master\PyGMI_files\Instruments_panels\Valves.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Panel(object):
    def setupUi(self, Panel):
        Panel.setObjectName("Panel")
        Panel.resize(1565, 1127)
        self.V1 = QtWidgets.QPushButton(Panel)
        self.V1.setGeometry(QtCore.QRect(960, 190, 61, 16))
        self.V1.setStyleSheet("background-color: rgb(170, 0, 0);\n"
"alternate-background-color: rgb(0, 170, 0);")
        self.V1.setCheckable(True)
        self.V1.setChecked(False)
        self.V1.setObjectName("V1")
        self.V2 = QtWidgets.QPushButton(Panel)
        self.V2.setGeometry(QtCore.QRect(1040, 190, 61, 16))
        self.V2.setAutoFillBackground(False)
        self.V2.setStyleSheet("background-color: rgb(170, 0, 0);\n"
"alternate-background-color: rgb(0, 170, 0);")
        self.V2.setCheckable(True)
        self.V2.setChecked(False)
        self.V2.setObjectName("V2")
        self.label = QtWidgets.QLabel(Panel)
        self.label.setGeometry(QtCore.QRect(100, 30, 1361, 1051))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("C:\\Users\\TuckerVana\\PycharmProjects\\GUI Project 2.0\\PyGMI-master\\PyGMI_files\\Instruments_panels\\../../../../../Pictures/Saved Pictures/Screenshot 2022-02-09 124355.png"))
        self.label.setObjectName("label")
        self.V3 = QtWidgets.QPushButton(Panel)
        self.V3.setGeometry(QtCore.QRect(970, 390, 61, 16))
        self.V3.setStyleSheet("background-color: rgb(170, 0, 0);\n"
"alternate-background-color: rgb(0, 170, 0);")
        self.V3.setCheckable(True)
        self.V3.setChecked(False)
        self.V3.setObjectName("V3")
        self.V4 = QtWidgets.QPushButton(Panel)
        self.V4.setGeometry(QtCore.QRect(1060, 390, 61, 16))
        self.V4.setStyleSheet("background-color: rgb(170, 0, 0);\n"
"alternate-background-color: rgb(0, 170, 0);")
        self.V4.setCheckable(True)
        self.V4.setChecked(False)
        self.V4.setObjectName("V4")
        self.V5 = QtWidgets.QPushButton(Panel)
        self.V5.setGeometry(QtCore.QRect(890, 250, 61, 16))
        self.V5.setStyleSheet("background-color: rgb(170, 0, 0);\n"
"alternate-background-color: rgb(0, 170, 0);")
        self.V5.setCheckable(True)
        self.V5.setChecked(False)
        self.V5.setObjectName("V5")
        self.V6 = QtWidgets.QPushButton(Panel)
        self.V6.setGeometry(QtCore.QRect(890, 300, 61, 16))
        self.V6.setStyleSheet("background-color: rgb(170, 0, 0);\n"
"alternate-background-color: rgb(0, 170, 0);")
        self.V6.setCheckable(True)
        self.V6.setChecked(False)
        self.V6.setObjectName("V6")
        self.V7 = QtWidgets.QPushButton(Panel)
        self.V7.setGeometry(QtCore.QRect(1150, 910, 61, 16))
        self.V7.setStyleSheet("background-color: rgb(170, 0, 0);\n"
"alternate-background-color: rgb(0, 170, 0);")
        self.V7.setCheckable(True)
        self.V7.setChecked(False)
        self.V7.setObjectName("V7")
        self.V9 = QtWidgets.QPushButton(Panel)
        self.V9.setGeometry(QtCore.QRect(870, 1010, 61, 16))
        self.V9.setStyleSheet("background-color: rgb(170, 0, 0);\n"
"alternate-background-color: rgb(0, 170, 0);")
        self.V9.setCheckable(True)
        self.V9.setChecked(False)
        self.V9.setObjectName("V9")
        self.V10 = QtWidgets.QPushButton(Panel)
        self.V10.setGeometry(QtCore.QRect(1020, 930, 61, 16))
        self.V10.setStyleSheet("background-color: rgb(170, 0, 0);\n"
"alternate-background-color: rgb(0, 170, 0);")
        self.V10.setCheckable(True)
        self.V10.setChecked(False)
        self.V10.setObjectName("V10")
        self.V11 = QtWidgets.QPushButton(Panel)
        self.V11.setGeometry(QtCore.QRect(750, 840, 61, 16))
        self.V11.setStyleSheet("background-color: rgb(170, 0, 0);\n"
"alternate-background-color: rgb(0, 170, 0);")
        self.V11.setCheckable(True)
        self.V11.setChecked(False)
        self.V11.setObjectName("V11")
        self.V12 = QtWidgets.QPushButton(Panel)
        self.V12.setGeometry(QtCore.QRect(720, 480, 61, 16))
        self.V12.setStyleSheet("background-color: rgb(170, 0, 0);\n"
"alternate-background-color: rgb(0, 170, 0);")
        self.V12.setCheckable(True)
        self.V12.setChecked(False)
        self.V12.setObjectName("V12")
        self.V13 = QtWidgets.QPushButton(Panel)
        self.V13.setGeometry(QtCore.QRect(540, 760, 61, 16))
        self.V13.setStyleSheet("background-color: rgb(170, 0, 0);\n"
"alternate-background-color: rgb(0, 170, 0);")
        self.V13.setCheckable(True)
        self.V13.setChecked(False)
        self.V13.setObjectName("V13")
        self.V14 = QtWidgets.QPushButton(Panel)
        self.V14.setGeometry(QtCore.QRect(510, 790, 61, 16))
        self.V14.setStyleSheet("background-color: rgb(170, 0, 0);\n"
"alternate-background-color: rgb(0, 170, 0);")
        self.V14.setCheckable(True)
        self.V14.setChecked(False)
        self.V14.setObjectName("V14")
        self.V15 = QtWidgets.QPushButton(Panel)
        self.V15.setGeometry(QtCore.QRect(440, 660, 61, 16))
        self.V15.setStyleSheet("background-color: rgb(170, 0, 0);\n"
"alternate-background-color: rgb(0, 170, 0);")
        self.V15.setCheckable(True)
        self.V15.setChecked(False)
        self.V15.setObjectName("V15")
        self.V16 = QtWidgets.QPushButton(Panel)
        self.V16.setGeometry(QtCore.QRect(510, 520, 61, 16))
        self.V16.setStyleSheet("background-color: rgb(170, 0, 0);\n"
"alternate-background-color: rgb(0, 170, 0);")
        self.V16.setCheckable(True)
        self.V16.setChecked(False)
        self.V16.setObjectName("V16")
        self.V18 = QtWidgets.QPushButton(Panel)
        self.V18.setGeometry(QtCore.QRect(290, 790, 61, 16))
        self.V18.setStyleSheet("background-color: rgb(170, 0, 0);\n"
"alternate-background-color: rgb(0, 170, 0);")
        self.V18.setCheckable(True)
        self.V18.setChecked(False)
        self.V18.setObjectName("V18")
        self.V19 = QtWidgets.QPushButton(Panel)
        self.V19.setGeometry(QtCore.QRect(650, 760, 61, 16))
        self.V19.setStyleSheet("background-color: rgb(170, 0, 0);\n"
"alternate-background-color: rgb(0, 170, 0);")
        self.V19.setCheckable(True)
        self.V19.setChecked(False)
        self.V19.setObjectName("V19")
        self.V20 = QtWidgets.QPushButton(Panel)
        self.V20.setGeometry(QtCore.QRect(440, 790, 61, 16))
        self.V20.setStyleSheet("background-color: rgb(170, 0, 0);\n"
"alternate-background-color: rgb(0, 170, 0);")
        self.V20.setCheckable(True)
        self.V20.setChecked(False)
        self.V20.setObjectName("V20")
        self.V21 = QtWidgets.QPushButton(Panel)
        self.V21.setGeometry(QtCore.QRect(380, 930, 61, 16))
        self.V21.setStyleSheet("background-color: rgb(170, 0, 0);\n"
"alternate-background-color: rgb(0, 170, 0);")
        self.V21.setCheckable(True)
        self.V21.setChecked(False)
        self.V21.setObjectName("V21")
        self.V22 = QtWidgets.QPushButton(Panel)
        self.V22.setGeometry(QtCore.QRect(1080, 520, 61, 16))
        self.V22.setStyleSheet("background-color: rgb(170, 0, 0);\n"
"alternate-background-color: rgb(0, 170, 0);")
        self.V22.setCheckable(True)
        self.V22.setChecked(False)
        self.V22.setObjectName("V22")
        self.V23 = QtWidgets.QPushButton(Panel)
        self.V23.setGeometry(QtCore.QRect(1080, 640, 61, 16))
        self.V23.setStyleSheet("background-color: rgb(170, 0, 0);\n"
"alternate-background-color: rgb(0, 170, 0);")
        self.V23.setCheckable(True)
        self.V23.setChecked(False)
        self.V23.setObjectName("V23")
        self.V8 = QtWidgets.QPushButton(Panel)
        self.V8.setGeometry(QtCore.QRect(1140, 1010, 61, 16))
        self.V8.setStyleSheet("background-color: rgb(170, 0, 0);\n"
"alternate-background-color: rgb(0, 170, 0);")
        self.V8.setCheckable(True)
        self.V8.setChecked(False)
        self.V8.setObjectName("V8")
        self.V24 = QtWidgets.QPushButton(Panel)
        self.V24.setGeometry(QtCore.QRect(1020, 560, 61, 16))
        self.V24.setStyleSheet("background-color: rgb(170, 0, 0);\n"
"alternate-background-color: rgb(0, 170, 0);")
        self.V24.setCheckable(True)
        self.V24.setChecked(False)
        self.V24.setObjectName("V24")
        self.V17 = QtWidgets.QPushButton(Panel)
        self.V17.setGeometry(QtCore.QRect(440, 390, 61, 16))
        self.V17.setStyleSheet("background-color: rgb(170, 0, 0);\n"
"alternate-background-color: rgb(0, 170, 0);")
        self.V17.setCheckable(True)
        self.V17.setChecked(False)
        self.V17.setObjectName("V17")
        self.label.raise_()
        self.V1.raise_()
        self.V2.raise_()
        self.V3.raise_()
        self.V4.raise_()
        self.V5.raise_()
        self.V6.raise_()
        self.V7.raise_()
        self.V9.raise_()
        self.V10.raise_()
        self.V11.raise_()
        self.V12.raise_()
        self.V13.raise_()
        self.V14.raise_()
        self.V15.raise_()
        self.V16.raise_()
        self.V18.raise_()
        self.V19.raise_()
        self.V20.raise_()
        self.V21.raise_()
        self.V22.raise_()
        self.V23.raise_()
        self.V8.raise_()
        self.V24.raise_()
        self.V17.raise_()

        self.retranslateUi(Panel)
        self.V1.clicked['bool'].connect(Panel.check_state) # type: ignore
        self.V2.clicked['bool'].connect(Panel.check_state) # type: ignore
        self.V3.clicked['bool'].connect(Panel.check_state) # type: ignore
        self.V4.clicked['bool'].connect(Panel.check_state) # type: ignore
        self.V5.clicked['bool'].connect(Panel.check_state) # type: ignore
        self.V6.clicked['bool'].connect(Panel.check_state) # type: ignore
        self.V7.clicked['bool'].connect(Panel.check_state) # type: ignore
        self.V10.clicked['bool'].connect(Panel.check_state) # type: ignore
        self.V9.clicked['bool'].connect(Panel.check_state) # type: ignore
        self.V11.clicked['bool'].connect(Panel.check_state) # type: ignore
        self.V12.clicked['bool'].connect(Panel.check_state) # type: ignore
        self.V13.clicked['bool'].connect(Panel.check_state) # type: ignore
        self.V15.clicked['bool'].connect(Panel.check_state) # type: ignore
        self.V14.clicked['bool'].connect(Panel.check_state) # type: ignore
        self.V16.clicked['bool'].connect(Panel.check_state) # type: ignore
        self.V22.clicked['bool'].connect(Panel.check_state) # type: ignore
        self.V23.clicked['bool'].connect(Panel.check_state) # type: ignore
        self.V19.clicked['bool'].connect(Panel.check_state) # type: ignore
        self.V21.clicked['bool'].connect(Panel.check_state) # type: ignore
        self.V18.clicked['bool'].connect(Panel.check_state) # type: ignore
        self.V20.clicked['bool'].connect(Panel.check_state) # type: ignore
        self.V8.clicked['bool'].connect(Panel.check_state) # type: ignore
        self.V24.clicked['bool'].connect(Panel.check_state) # type: ignore
        self.V17.clicked['bool'].connect(Panel.check_state) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Panel)

    def retranslateUi(self, Panel):
        _translate = QtCore.QCoreApplication.translate
        Panel.setWindowTitle(_translate("Panel", "Valves"))
        self.V1.setText(_translate("Panel", "VALVE 1"))
        self.V2.setText(_translate("Panel", "VALVE 2"))
        self.V3.setText(_translate("Panel", "VALVE 3"))
        self.V4.setText(_translate("Panel", "VALVE 4"))
        self.V5.setText(_translate("Panel", "VALVE 5"))
        self.V6.setText(_translate("Panel", "VALVE 6"))
        self.V7.setText(_translate("Panel", "VALVE 7"))
        self.V9.setText(_translate("Panel", "VALVE 9"))
        self.V10.setText(_translate("Panel", "VALVE 10"))
        self.V11.setText(_translate("Panel", "VALVE 11"))
        self.V12.setText(_translate("Panel", "VALVE 12"))
        self.V13.setText(_translate("Panel", "VALVE 13"))
        self.V14.setText(_translate("Panel", "VALVE 14"))
        self.V15.setText(_translate("Panel", "VALVE 15"))
        self.V16.setText(_translate("Panel", "VALVE 16"))
        self.V18.setText(_translate("Panel", "VALVE 18"))
        self.V19.setText(_translate("Panel", "VALVE 19"))
        self.V20.setText(_translate("Panel", "VALVE 20"))
        self.V21.setText(_translate("Panel", "VALVE 21"))
        self.V22.setText(_translate("Panel", "VALVE 22"))
        self.V23.setText(_translate("Panel", "VALVE 23"))
        self.V8.setText(_translate("Panel", "VALVE 8"))
        self.V24.setText(_translate("Panel", "VALVE 24"))
        self.V17.setText(_translate("Panel", "VALVE 17"))
# from . import image_rc
